### ISSUE TITLE
TestLegacyInviteJSCreate failed

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/go-ssb#249]
Documenting failing tests as I find them:

```
=== RUN   TestLegacyInviteJSCreate
2022/12/10 16:10:23 saved identity @GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=.ed25519 to testrun/TestLegacyInviteJSCreate/secret
    interop_test.go:123: go-sbot: @GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=.ed25519
    invite_legacy_test.go:50: addr: net:127.0.0.1:38783~shs:GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=
    interop_test.go:152: starting client alice
TAP version 13
# alice
# sbot spawned, running before
    interop_test.go:200: JS alice:14 @lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519
ok 1 null
Trace: deprecated api used: ssb-ref.parseAddress
    at Object.parseAddress (/home/go-ssb/go-ssb/tests/node_modules/ssb-ref/index.js:99:15)
    at Object.<anonymous> (/home/go-ssb/go-ssb/tests/node_modules/ssb-invite/index.js:97:24)
    at apply (/home/go-ssb/go-ssb/tests/node_modules/muxrpc-validation/index.js:197:15)
    at Object.<anonymous> (/home/go-ssb/go-ssb/tests/node_modules/muxrpc-validation/index.js:86:14)
    at Object.hooked [as create] (/home/go-ssb/go-ssb/tests/node_modules/hoox/index.js:10:15)
    at eval (eval at <anonymous> (/home/go-ssb/go-ssb/tests/sbot_client.js:102:3), <anonymous>:18:16)
    at /home/go-ssb/go-ssb/tests/node_modules/ssb-db/minimal.js:163:23
    at AsyncJobQueue.runAll (/home/go-ssb/go-ssb/tests/node_modules/ssb-db/util.js:207:7)
    at Object.cb (/home/go-ssb/go-ssb/tests/node_modules/ssb-db/minimal.js:106:15)
    at /home/go-ssb/go-ssb/tests/node_modules/append-batch/index.js:22:38
ok 2 null
ok 3 null
# ssb-js: invite saved!
# dialing:net:127.0.0.1:38783~shs:GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=
level=debug t=1.572635611s peer=<@lf2y.ed25519> conn=mkHandler err="nope - access denied"
ok 4 connected
    invite_legacy_test.go:110: localhost:51431:@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519~mz0Td8TvgxX0PvOA9l1L8NdH1wB0gxxoJ0iWTDM0bKE=
ssb-friends: get legacy api used
# rpc closed:@+tVOKRqs0KObXfp7j5qTbuHF2aI/lHNSztNWh+ueb7c=.ed25519
level=debug t=3.072122787s event=update-replicate feed-want-count=0 hops=0 took=95.327µs
not ok 5 alice timed out after 15000ms
  ---
    operator: fail
    stack: |-
      Error: alice timed out after 15000ms
          at Test.assert [as _assert] (/home/go-ssb/go-ssb/tests/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/home/go-ssb/go-ssb/tests/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/home/go-ssb/go-ssb/tests/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/home/go-ssb/go-ssb/tests/node_modules/tape/lib/test.js:91:32)
          at Timeout._onTimeout (/home/go-ssb/go-ssb/tests/node_modules/tape/lib/test.js:173:14)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)
  ...
# test timeout

JS Sbot process returned
    interop_test.go:152: starting client alice
TAP version 13
# alice
# sbot spawned, running before
    interop_test.go:200: JS alice:15 @lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519
# dialing:net:127.0.0.1:38783~shs:GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=
ok 1 connected
level=debug t=21.222214314s plugin=ebt event=replicating version=3
level=debug t=21.266829154s unit=gossip fr=<@GNqx.ed25519> event=gossiptx n=17 starting=0
level=error t=21.673716309s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:1): invalid signature"
level=error t=21.675994996s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:2): invalid signature"
level=error t=21.679634525s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:3): invalid signature"
level=error t=21.684468263s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:4): invalid signature"
level=error t=21.688404123s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:5): invalid signature"
level=error t=21.692369513s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:6): invalid signature"
level=error t=21.695736875s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:7): invalid signature"
level=error t=21.699166008s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:8): invalid signature"
level=error t=21.702621512s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:9): invalid signature"
level=error t=21.706066847s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:10): invalid signature"
level=error t=21.709415774s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:11): invalid signature"
level=error t=21.712641168s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:12): invalid signature"
level=error t=21.715523212s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:13): invalid signature"
level=error t=21.71960502s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:14): invalid signature"
level=error t=21.729021973s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:15): invalid signature"
level=error t=21.731636186s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:16): invalid signature"
level=error t=21.734385954s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:17): invalid signature"
level=error t=21.736480726s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:18): invalid signature"
level=error t=21.739537245s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:19): invalid signature"
level=error t=21.74122166s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:20): invalid signature"
level=error t=21.744233828s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:21): invalid signature"
level=error t=21.745893074s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:22): invalid signature"
level=error t=21.748918524s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:23): invalid signature"
level=error t=21.750684006s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:24): invalid signature"
level=error t=21.753851333s plugin=ebt error="ValidateNext(<@lf2y.ed25519>:0): first message has to have sequence 1, got 25"
level=error t=21.755345287s plugin=ebt error="ValidateNext(<@lf2y.ed25519>:0): first message has to have sequence 1, got 26"
level=debug t=23.310113892s event=update-replicate feed-want-count=1 hops=0 took=148.926µs
level=debug t=23.695584908s plugin=ebt r=<@lf2y.ed25519> event="loop exited"
# now should have feed:@GNqxgk8omP6COZQ//fwZC/GDd4JsKMsfUBJOmZaMRes=.ed25519
ok 2 query worked
ok 3 got all the messages
ok 4 final publish
level=debug t=23.741709264s plugin=ebt event=replicating version=3
level=error t=23.833929289s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:1): invalid signature"
level=error t=23.834675422s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:2): invalid signature"
level=error t=23.835346771s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:3): invalid signature"
level=error t=23.835974631s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:4): invalid signature"
level=error t=23.836652539s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:5): invalid signature"
level=error t=23.83733097s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:6): invalid signature"
level=error t=23.837957795s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:7): invalid signature"
level=error t=23.838604323s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:8): invalid signature"
level=error t=23.839240218s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:9): invalid signature"
level=error t=23.840410766s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:10): invalid signature"
level=error t=23.84198229s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:11): invalid signature"
level=error t=23.843420614s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:12): invalid signature"
level=error t=23.844989603s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:13): invalid signature"
level=error t=23.845832357s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:14): invalid signature"
level=error t=23.846511773s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:15): invalid signature"
level=error t=23.847155651s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:16): invalid signature"
level=error t=23.847765116s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:17): invalid signature"
level=error t=23.848386141s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:18): invalid signature"
level=error t=23.849017608s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:19): invalid signature"
level=error t=23.849640335s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:20): invalid signature"
level=error t=23.850258313s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:21): invalid signature"
level=error t=23.850854596s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:22): invalid signature"
level=error t=23.851474024s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:23): invalid signature"
level=error t=23.852120854s plugin=ebt error="message(<@lf2y.ed25519>:0) verify failed: ssb Verify(@lf2ygyETFeLf/jOBds0N6filb3lJjt4DfF9YrgQ1J4Q=.ed25519:24): invalid signature"
level=error t=23.852778782s plugin=ebt error="ValidateNext(<@lf2y.ed25519>:0): first message has to have sequence 1, got 25"
level=error t=23.853532016s plugin=ebt error="ValidateNext(<@lf2y.ed25519>:0): first message has to have sequence 1, got 26"
level=error t=23.854330483s plugin=ebt error="ValidateNext(<@lf2y.ed25519>:0): first message has to have sequence 1, got 27"
# closed sbot

1..4
# tests 4
# pass  4

# ok

JS Sbot process returned
level=debug t=26.759278634s plugin=ebt r=<@lf2y.ed25519> event="loop exited"
    interop_test.go:282: 
        	Error Trace:	/home/go-ssb/go-ssb/tests/interop_test.go:282
        	            				/home/go-ssb/go-ssb/tests/invite_legacy_test.go:164
        	Error:      	Received unexpected error:
        	            	cmd wait failed: exit status 1
        	Test:       	TestLegacyInviteJSCreate
--- FAIL: TestLegacyInviteJSCreate (26.76s)
level=debug t=26.762161432s event="network listen loop exited"
level=warn t=26.762258307s unit=gossip event="live qry on rxlog exited"
level=debug t=26.762480264s event="sbot closing" msg="connections closed"
level=debug t=26.762507249s event="sbot closing" msg="waited for indexes to close"
```

**Comment by KyleMaas** [comment]
Related to #237
